name: Favorites anime and currently watching
uses: lowlighter/metrics@latest
with:
  filename: anilist.anime.svg
  token: NOT_NEEDED
  base: ""
  plugin_anilist: yes
  plugin_anilist_medias: anime
  plugin_anilist_sections: favorites
  plugin_anilist_limit: 5

